[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
dao_voting = "3DfPXqokn9LqENng2DpJFebPGTFCUwTfLRyhxb3gFFH7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\ABKen\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
